# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
         fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - id: compute_tag
      uses: craig-day/compute-tag@v15
      with:
        github_token: ${{ github.token }}
        version_type: patch

    - shell: bash
      run: |
        echo "::notice::Generated tag is '${{ steps.compute_tag.outputs.next_tag }}'"

    - name: Create a new tag
      run: |
        go install github.com/ogen-go/ogen/cmd/ogen@latest        
        ogen --target ontrac/api/go -package ontracapi --clean openapi_spec/spec.yaml
        git tag '${{ steps.compute_tag.outputs.next_tag }}'
        git push --tags
        

